name: Gradle test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pusername=${{ github.actor }} -Ppassword=${{ secrets.GITHUB_TOKEN }} --stacktrace --info
    - name: Test & Check with Gradle
      run: ./gradlew check -Pusername=${{ github.actor }} -Ppassword=${{ secrets.GITHUB_TOKEN }} --stacktrace --info
    - name: Int test with Gradle
      run: ./gradlew dockerinttest -Pusername=${{ github.actor }} -Ppassword=${{ secrets.GITHUB_TOKEN }} --stacktrace --info
